var data = [
    {id: 1,
     title: "My Visual Partner",
     featured: true,
     short_title: "MVP",
     type: "iOS_app",
     icon: "Icon.jpg",
     tagline: "It is like uber for tinder",
     date: "September 2016",
     description: "You can now write a very nice beautiful discritpion that includes many important details and whatnot about the project.",
     detailed_description: "MVP - My Visual Partner provides a system that encourages independence for getting ready for user defined events. <br /><br />MVP allows users to create and schedule events. Then the user specifies the items that are required for the event. Once the event is created the user will be promoted and have a visual checklist to insure they find all of his or her items at the events specified time.",
     website_link: "google.com",
     live_product_link: "Google"
    }, 
    {
     id: 2,
     title: "ICE",
     featured: false,
     short_title: "ICE",
     type: "iOS_app",
     icon: "Icon.jpg",
     tagline: "It is like uber for tinder",
     date: "September 2016",
     description: "You can now write a very nice beautiful discritpion that includes many important details and whatnot about the project.",
     detailed_description: "Here is the super detailed description...",
     website_link: "google.com",
     live_product_link: "Google"
    }, 
    {
     id: 3,
     title: "Best Mobile App Cal Hacks 3.0",
     featured: false,
     short_title: "DoctorWatson",
     icon: "Icon.jpg",
     type: "award",
     tagline: "It is like uber for tinder",
     date: "November 2016",
     description: "You can now write a very nice beautiful discritpion that includes many important details and whatnot about the project.",
     detailed_description: "Here is the super detailed description...",
     website_link: "google.com",
     live_product_link: "Google"
    }, 
    {
     id: 4,
     title: "Doctor Watson",
     featured: false,
     short_title: "DoctorWatson",
     icon: "Icon.jpg",
     type: "iOS_app",
     tagline: "It is like uber for tinder",
     date: "September 2016",
     description: "You can now write a very nice beautiful discritpion that includes many important details and whatnot about the project.",
     detailed_description: "Here is the super detailed description...",
     website_link: "google.com",
     live_product_link: ""
    }, 
    {
     id: 5,
     title: "IT worked!!",
     featured: false,
     short_title: "DoctorWatson",
     icon: "Icon.jpg",
     type: "iOS_app",
     tagline: "It is like uber for tinder",
     date: "September 2016",
     description: "You can now write a very nice beautiful discritpion that includes many important details and whatnot about the project.",
     detailed_description: "Here is the super detailed description...",
     website_link: "google.com",
     live_product_link: "Google"
    }
];

