var data = [
    {id: 1,
     title: "My Visual Partner",
     featured: true,
     short_title: "MVP",
     type: "iOS_app",
     icon: "Icon.jpg",
     tagline: "Encourages independence through personalized visual aids",
     date: "September 2016",
     description: "iOS app that provides a system to encourage independence for individuals with learning differences",
     detailed_description: "MVP - My Visual Partner provides a system that encourages independence for getting ready for user defined events. <br /><br />MVP allows users to create and schedule events. Then the user specifies the items that are required for the event. Once the event is created the user will be promoted and have a visual checklist to insure they find all of his or her items at the events specified time.",
     website_link: "google.com",
     live_product_link: "Google"
    }, 
    {
     id: 2,
     title: "ICE",
     featured: false,
     short_title: "ICE",
     type: "iOS_app",
     icon: "Icon.jpg",
     tagline: "An intelligent collaborative environment for the classroom",
     date: "August 2015",
     description: "ICE - Interactive Collaborative Environment provides a platform that delivers Reminders, Scheduling, an Aggregated Dashboard, and Collaboration!",
     detailed_description: "Here is the super detailed description...",
     website_link: "google.com",
     live_product_link: "Google"
    }, 
    {
     id: 3,
     title: "Best Mobile App Cal Hacks 3.0",
     featured: false,
     short_title: "TravelChest",
     icon: "Icon.jpg",
     type: "award",
     tagline: "It is like uber for tinder",
     date: "November 2016",
     description: "You can now write a very nice beautiful discritpion that includes many important details and whatnot about the project.",
     detailed_description: "Here is the super detailed description...",
     website_link: "https://devpost.com/software/travel-chest-pdye6a",
     live_product_link: ""
    }, 
    {
     id: 4,
     title: "Most Polished App at HackBCA III",
     featured: false,
     short_title: "DoctorWatson",
     icon: "Icon.jpg",
     type: "award",
     tagline: "Doctor Watson - Receive professional medical feedback instantly",
     date: "April 2016",
     description: "DoctorWatson is an iOS app that utilizes the power of IMB's Watson AI to process the users naturally spoken medical complaint and then match the user with the most relevant doctor available",
     detailed_description: "DoctorWatson utilizes the power of IMB's Watson AI to process the users naturally spoken medical complaint. Then through mapping the words and phrases through relevance we determined the best fit specialist type to assist the user. Next we parse through our database of Doctor users and find a doctor that is free and can best assist the user. We then show the best fit doctor to the user, if the user likes the doctor they can then chat and discuss the health issue.",
     website_link: "https://devpost.com/software/doctorwatson-9rpvot",
     live_product_link: ""
    }, 
    {
     id: 5,
     title: "High School LaVie",
     featured: false,
     short_title: "HSLaVie",
     icon: "Icon.jpg",
     type: "iOS_app",
     tagline: "Prepare for college apps with High School LaVie",
     date: "September 2016",
     description: "High School LaVie is an iOS app that keeps track of essential elements and streamlines the college application process.",
     detailed_description: "High School LaVie allows students to effectively and elegantly record high school achievements. This is critically important for the college application process and prevents an \'Oh shoot\' moment when you are applying for college and you forget what spectacular things you were doing back in 9th grade. HS LaVie solves this problem :) Quickly, create, save, and view activities. Reminders, will encourage you to do little bits every so often in order to prevent forgetting or putting off recording your achievements. <br /><br /> Download High School LaVie and become more prepared for the college application process.",
     website_link: "http://mylavie.com",
     live_product_link: "https://itunes.apple.com/us/app/high-school-lavie/id1086503521?mt=8"
    },
    {
     id: 6,
     title: "Profesional LaVie",
     featured: false,
     short_title: "ProLaVie",
     icon: "Icon.jpg",
     type: "iOS_app",
     tagline: "Prepare for annual reviews with Professional LaVie",
     date: "September 2016",
     description: "High School LaVie is an iOS app that keeps track of essential elements and streamlines the college application process.",
     detailed_description: "High School LaVie allows students to effectively and elegantly record high school achievements. This is critically important for the college application process and prevents an \'Oh shoot\' moment when you are applying for college and you forget what spectacular things you were doing back in 9th grade. HS LaVie solves this problem :) Quickly, create, save, and view activities. Reminders, will encourage you to do little bits every so often in order to prevent forgetting or putting off recording your achievements. <br /><br /> Download High School LaVie and become more prepared for the college application process.",
     website_link: "google.com",
     live_product_link: "Google"
    },
    {
     id: 7,
     title: "Best Social/Civic Hacking Hack",
     featured: false,
     short_title: "Beacons",
     icon: "Icon.jpg",
     type: "award",
     tagline: "Beacons - promoting civic welfare through encouraging personal responsibility and communal empathy.",
     date: "September 2016",
     description: "High School LaVie is an iOS app that keeps track of essential elements and streamlines the college application process.",
     detailed_description: "Provides connections to skilled individuals in the area for those who require the completion of a specific task. The functionality of the application is divided into the medical requests, the miscellaneous utility requests, and the social requests. The user places a Beacon for a specific problem they desire completed. All individuals with the application downloaded within a preset radius and fulfilling a basic skill requirement are notified of the Beacon. When installing the application, the user inputs their skills. Sensitive skills such as emergency medical abilities are vetted.",
     website_link: "https://devpost.com/software/beacons",
     live_product_link: ""
    },
    {
     id: 8,
     title: "How to build a great product series",
     featured: false,
     short_title: "ProLaVie",
     icon: "Icon.jpg",
     type: "medium_article",
     tagline: "Prepare for annual reviews with Professional LaVie",
     date: "November 2016",
     description: "High School LaVie is an iOS app that keeps track of essential elements and streamlines the college application process.",
     detailed_description: "High School LaVie allows students to effectively and elegantly record high school achievements. This is critically important for the college application process and prevents an \'Oh shoot\' moment when you are applying for college and you forget what spectacular things you were doing back in 9th grade. HS LaVie solves this problem :) Quickly, create, save, and view activities. Reminders, will encourage you to do little bits every so often in order to prevent forgetting or putting off recording your achievements. <br /><br /> Download High School LaVie and become more prepared for the college application process.",
     website_link: "google.com",
     live_product_link: "Google"
    },
    {
     id: 9,
     title: "How to build a great product series",
     featured: false,
     short_title: "ProLaVie",
     icon: "Icon.jpg",
     type: "medium_article",
     tagline: "Prepare for annual reviews with Professional LaVie",
     date: "November 2016",
     description: "High School LaVie is an iOS app that keeps track of essential elements and streamlines the college application process.",
     detailed_description: "High School LaVie allows students to effectively and elegantly record high school achievements. This is critically important for the college application process and prevents an \'Oh shoot\' moment when you are applying for college and you forget what spectacular things you were doing back in 9th grade. HS LaVie solves this problem :) Quickly, create, save, and view activities. Reminders, will encourage you to do little bits every so often in order to prevent forgetting or putting off recording your achievements. <br /><br /> Download High School LaVie and become more prepared for the college application process.",
     website_link: "google.com",
     live_product_link: "Google"
    }
];